FROM python:3.8-slim-buster
WORKDIR /HZZ_app
COPY /HZZ_app /HZZ_app
ENV PYTHONPATH /HZZ_app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/requirements_webserver.txt
CMD ["python", "scripts/webserver/webserver_comm.py"]